export const TYPES = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    GETMYDATA: 'GETMYDATA',
    REGISTER: 'REGISTER',
    CHECKEMAIL: 'CHECKEMAIL',
    RESETREGISTERSTATE: 'RESETREGISTERSTATE',
    DELETEACCOUNT: 'DELETEACCOUNT',
    RESETPERSONALDATASTATE: 'RESETPERSONALDATASTATE'
}